export const MUTED_TEXT_COLOR = "#a3a3a3";
export const EMPHASIZED_TEXT_COLOR = "#e5e5e5";
export const ERROR_TEXT_COLOR = "#f87171";
export const FIELD_BACKGROUND_COLOR = "#262626";
export const FIELD_BORDER_COLOR = "#404040";
export const PRIMARY_BUTTON_BACKGROUND_COLOR = "#047857";
export const PRIMARY_BUTTON_HOVER_BACKGROUND_COLOR = "#059669";
export const SECONDARY_BUTTON_HOVER_BACKGROUND_COLOR = "#262626";

export const PRIMARY_BUTTON_HOVER_STYLE = {
	bg: PRIMARY_BUTTON_HOVER_BACKGROUND_COLOR,
};
export const SECONDARY_BUTTON_HOVER_STYLE = {
	bg: SECONDARY_BUTTON_HOVER_BACKGROUND_COLOR,
};
export const DISABLED_BUTTON_STYLE = { opacity: 0.5 };
